// DATA MODULE

const RAW_DATA = [
{id:1,therapy:"Onco",event:"Prostate Cancer CME",month:"February",date:"7-Feb-2025",type:"NSP",attendees:59,salesperson:null,reported:true,kols:[]},
{id:2,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"February",date:"11-Feb-2025",type:"NSP",attendees:66,salesperson:null,reported:true,kols:[]},
{id:3,therapy:"Onco",event:"ISP Prime Meet + Local (Chandigarh, Delhi, Nashik)",month:"February",date:"28-Feb-2025",type:"ISP",attendees:85,salesperson:null,reported:true,kols:[]},
{id:4,therapy:"Onco",event:"Prostate Cancer CME",month:"March",date:"11-Mar-2025",type:"NSP",attendees:94,salesperson:null,reported:true,kols:[]},
{id:5,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"March",date:"11-Mar-2025",type:"NSP",attendees:42,salesperson:null,reported:true,kols:[]},
{id:6,therapy:"Onco",event:"Prostate Cancer CME",month:"March",date:"12-Mar-2025",type:"NSP",attendees:44,salesperson:null,reported:true,kols:[]},
{id:7,therapy:"Onco",event:"Prostate Cancer CME",month:"March",date:"18-Mar-2025",type:"NSP",attendees:63,salesperson:null,reported:true,kols:[]},
{id:8,therapy:"Onco",event:"Prostate Cancer CME",month:"March",date:"20-Mar-2025",type:"NSP",attendees:48,salesperson:null,reported:true,kols:[]},
{id:9,therapy:"Onco",event:"Prostate Cancer CME",month:"March",date:"22-Mar-2025",type:"NSP",attendees:55,salesperson:null,reported:true,kols:[]},
{id:10,therapy:"Onco",event:"Prostate Cancer CME",month:"March",date:"25-Mar-2025",type:"NSP",attendees:42,salesperson:null,reported:true,kols:[]},
{id:11,therapy:"Onco",event:"Prostate Cancer CME",month:"March",date:"26-Mar-2025",type:"NSP",attendees:64,salesperson:null,reported:true,kols:[]},
{id:12,therapy:"Onco",event:"Prostate Cancer CME",month:"March",date:"26-Mar-2025",type:"NSP",attendees:58,salesperson:null,reported:true,kols:[]},
{id:13,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"March",date:"27-Mar-2025",type:"NSP",attendees:54,salesperson:null,reported:true,kols:[]},
{id:14,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"March",date:"27-Mar-2025",type:"NSP",attendees:43,salesperson:null,reported:true,kols:[]},
{id:15,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"March",date:"29-Mar-2025",type:"NSP",attendees:43,salesperson:null,reported:true,kols:[]},
{id:16,therapy:"Onco",event:"Prostate Cancer CME",month:"April",date:"8-Apr-2025",type:"NSP",attendees:59,salesperson:null,reported:true,kols:[]},
{id:17,therapy:"Onco",event:"Prostate Cancer CME",month:"April",date:"10-Apr-2025",type:"NSP",attendees:68,salesperson:null,reported:true,kols:[]},
{id:18,therapy:"Onco",event:"Prostate Cancer CME",month:"April",date:"18-Apr-2025",type:"NSP",attendees:81,salesperson:null,reported:true,kols:[]},
{id:19,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"April",date:"25-Apr-2025",type:"NSP",attendees:49,salesperson:null,reported:true,kols:[]},
{id:20,therapy:"Onco",event:"Prostate Cancer CME",month:"April",date:"29-Apr-2025",type:"NSP",attendees:47,salesperson:null,reported:true,kols:[]},
{id:21,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"April",date:"29-Apr-2025",type:"NSP",attendees:64,salesperson:null,reported:true,kols:[]},
{id:22,therapy:"Onco",event:"Prostate Cancer CME",month:"April",date:"30-Apr-2025",type:"NSP",attendees:54,salesperson:null,reported:true,kols:[]},
{id:23,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"May",date:"4-May-2025",type:"NSP",attendees:47,salesperson:null,reported:true,kols:[]},
{id:24,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"May",date:"8-May-2025",type:"NSP",attendees:42,salesperson:null,reported:true,kols:[]},
{id:25,therapy:"Onco",event:"Prostate Cancer CME",month:"May",date:"9-May-2025",type:"NSP",attendees:75,salesperson:null,reported:true,kols:[]},
{id:26,therapy:"Onco",event:"Prostate Cancer CME",month:"May",date:"20-May-2025",type:"NSP",attendees:61,salesperson:null,reported:true,kols:[]},
{id:27,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"May",date:"21-May-2025",type:"NSP",attendees:44,salesperson:null,reported:true,kols:[]},
{id:28,therapy:"Onco",event:"Prostate Cancer CME",month:"May",date:"27-May-2025",type:"NSP",attendees:82,salesperson:null,reported:true,kols:[]},
{id:29,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"May",date:"28-May-2025",type:"NSP",attendees:116,salesperson:null,reported:true,kols:[]},
{id:30,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"May",date:"30-May-2025",type:"NSP",attendees:41,salesperson:null,reported:true,kols:[]},
{id:31,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"June",date:"5-Jun-2025",type:"NSP",attendees:73,salesperson:null,reported:true,kols:[]},
{id:32,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"June",date:"7-Jun-2025",type:"NSP",attendees:49,salesperson:null,reported:true,kols:[]},
{id:33,therapy:"Onco",event:"Prostate Cancer CME",month:"June",date:"10-Jun-2025",type:"NSP",attendees:57,salesperson:null,reported:true,kols:[]},
{id:34,therapy:"Opthal",event:"Bayer I-Sight meeting 7:30pm",month:"June",date:"10-Jun-2025",type:"NSP",attendees:55,salesperson:null,reported:true,kols:[]},
{id:35,therapy:"Opthal",event:"Bayer I-Sight meeting 8pm",month:"June",date:"13-Jun-2025",type:"NSP",attendees:48,salesperson:null,reported:true,kols:[]},
{id:36,therapy:"Opthal",event:"Bayer I-Sight meeting 7:30pm",month:"June",date:"13-Jun-2025",type:"NSP",attendees:56,salesperson:null,reported:true,kols:[]},
{id:37,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"June",date:"21-Jun-2025",type:"NSP",attendees:44,salesperson:null,reported:true,kols:[]},
{id:38,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"June",date:"24-Jun-2025",type:"NSP",attendees:40,salesperson:null,reported:true,kols:[]},
{id:39,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"June",date:"20-Jun-2025",type:"NSP",attendees:57,salesperson:null,reported:true,kols:[]},
{id:40,therapy:"Opthal",event:"Bayer I-Sight meeting 8:30pm",month:"June",date:"25-Jun-2025",type:"NSP",attendees:31,salesperson:null,reported:true,kols:[]},
{id:41,therapy:"Onco",event:"Prostate Cancer CME",month:"June",date:"26-Jun-2025",type:"NSP",attendees:50,salesperson:null,reported:true,kols:[]},
{id:42,therapy:"Opthal",event:"Bayer I-Sight meeting 8:30",month:"June",date:"24-Jun-2025",type:"NSP",attendees:44,salesperson:null,reported:true,kols:[]},
{id:43,therapy:"Opthal",event:"Bayer I-Sight meeting 7:30pm",month:"June",date:"25-Jun-2025",type:"NSP",attendees:88,salesperson:null,reported:true,kols:[]},
{id:44,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"June",date:"27-Jun-2025",type:"NSP",attendees:43,salesperson:null,reported:true,kols:[]},
{id:45,therapy:"Opthal",event:"Bayer I-Sight meeting 7:30pm",month:"June",date:"30-Jun-2025",type:"NSP",attendees:61,salesperson:null,reported:true,kols:[]},
{id:46,therapy:"Opthal",event:"Bayer I-Sight meeting 8:00pm",month:"June",date:"30-Jun-2025",type:"NSP",attendees:37,salesperson:null,reported:true,kols:[]},
{id:47,therapy:"Onco",event:"Bayer ISP 2pm",month:"July",date:"1-Jul-2025",type:"ISP",attendees:29,salesperson:null,reported:true,kols:[]},
{id:48,therapy:"Onco",event:"Bayer ISP 8pm",month:"July",date:"1-Jul-2025",type:"ISP",attendees:26,salesperson:null,reported:true,kols:[]},
{id:49,therapy:"Onco",event:"Bayer ISP 2pm",month:"July",date:"3-Jul-2025",type:"ISP",attendees:22,salesperson:null,reported:true,kols:[]},
{id:50,therapy:"Onco",event:"Bayer ISP 8pm",month:"July",date:"5-Jul-2025",type:"ISP",attendees:20,salesperson:null,reported:true,kols:[]},
{id:51,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"July",date:"17-Jul-2025",type:"NSP",attendees:31,salesperson:null,reported:true,kols:[]},
{id:52,therapy:"Onco",event:"Prostate Cancer CME",month:"July",date:"11-Jul-2025",type:"NSP",attendees:35,salesperson:null,reported:true,kols:[]},
{id:53,therapy:"Onco",event:"Prostate Cancer CME",month:"July",date:"22-Jul-2025",type:"NSP",attendees:43,salesperson:null,reported:true,kols:[]},
{id:54,therapy:"Onco",event:"Prostate Cancer CME",month:"July",date:"29-Jul-2025",type:"NSP",attendees:53,salesperson:null,reported:true,kols:[]},
{id:55,therapy:"Onco",event:"Prostate Cancer CME",month:"July",date:"28-Jul-2025",type:"NSP",attendees:48,salesperson:null,reported:true,kols:[]},
{id:56,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"July",date:"30-Jul-2025",type:"NSP",attendees:58,salesperson:null,reported:true,kols:[]},
{id:57,therapy:"Onco",event:"Prostate Cancer CME",month:"August",date:"4-Aug-2025",type:"NSP",attendees:44,salesperson:null,reported:true,kols:[]},
{id:58,therapy:"Onco",event:"Prostate Cancer CME",month:"August",date:"5-Aug-2025",type:"NSP",attendees:56,salesperson:null,reported:true,kols:[]},
{id:59,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"August",date:"19-Aug-2025",type:"NSP",attendees:39,salesperson:null,reported:true,kols:[]},
{id:60,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"August",date:"23-Aug-2025",type:"NSP",attendees:38,salesperson:null,reported:true,kols:[]},
{id:61,therapy:"Onco",event:"Bayer I-Sight meeting",month:"August",date:"28-Aug-2025",type:"NSP",attendees:59,salesperson:null,reported:true,kols:[]},
{id:62,therapy:"Opthal",event:"Bayer I-Sight meeting 7:30pm",month:"August",date:"29-Aug-2025",type:"NSP",attendees:65,salesperson:null,reported:true,kols:[]},
{id:63,therapy:"Opthal",event:"Bayer I-Sight meeting 8:30pm",month:"August",date:"29-Aug-2025",type:"NSP",attendees:49,salesperson:null,reported:true,kols:[]},
{id:64,therapy:"Onco",event:"Prostate Cancer CME",month:"September",date:"4-Sept-2025",type:"NSP",attendees:72,salesperson:null,reported:true,kols:[]},
{id:65,therapy:"Onco",event:"Prostate Cancer CME",month:"September",date:"5-Sept-2025",type:"NSP",attendees:48,salesperson:null,reported:true,kols:[]},
{id:66,therapy:"Onco",event:"Prostate Cancer CME",month:"September",date:"9-Sept-2025",type:"NSP",attendees:45,salesperson:null,reported:true,kols:[]},
{id:67,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"September",date:"11-Sept-2025",type:"NSP",attendees:45,salesperson:null,reported:true,kols:[]},
{id:68,therapy:"Onco",event:"Prostate Cancer CME",month:"September",date:"12-Sept-2025",type:"NSP",attendees:50,salesperson:null,reported:true,kols:[]},
{id:69,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"September",date:"12-Sept-2025",type:"NSP",attendees:40,salesperson:null,reported:true,kols:[]},
{id:70,therapy:"Onco",event:"Prostate Cancer CME",month:"September",date:"13-Sept-2025",type:"NSP",attendees:35,salesperson:null,reported:true,kols:[]},
{id:71,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"September",date:"14-Sept-2025",type:"NSP",attendees:33,salesperson:null,reported:true,kols:[]},
{id:72,therapy:"Onco",event:"Prostate Cancer CME",month:"September",date:"16-Sept-2025",type:"NSP",attendees:60,salesperson:null,reported:true,kols:[]},
{id:73,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"September",date:"16-Sept-2025",type:"NSP",attendees:42,salesperson:null,reported:true,kols:[]},
{id:74,therapy:"Onco",event:"Prostate Cancer CME (Only Link)",month:"September",date:"16-Sept-2025",type:"NSP",attendees:50,salesperson:null,reported:true,kols:[]},
{id:75,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"September",date:"17-Sept-2025",type:"NSP",attendees:58,salesperson:null,reported:true,kols:[]},
{id:76,therapy:"Onco",event:"Prostate Cancer CME",month:"September",date:"17-Sept-2025",type:"NSP",attendees:42,salesperson:null,reported:true,kols:[]},
{id:77,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"September",date:"19-Sept-2025",type:"NSP",attendees:45,salesperson:null,reported:true,kols:[]},
{id:78,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"September",date:"20-Sept-2025",type:"NSP",attendees:40,salesperson:null,reported:true,kols:[]},
{id:79,therapy:"Onco",event:"Prostate Cancer CME",month:"September",date:"20-Sept-2025",type:"NSP",attendees:39,salesperson:null,reported:true,kols:[]},
{id:80,therapy:"Onco",event:"Prostate Cancer CME",month:"September",date:"23-Sept-2025",type:"NSP",attendees:48,salesperson:null,reported:true,kols:[]},
{id:81,therapy:"Onco",event:"Prostate Cancer CME",month:"September",date:"24-Sept-2025",type:"NSP",attendees:42,salesperson:null,reported:true,kols:[]},
{id:82,therapy:"Opthal",event:"Bayer I-Sight Meeting",month:"September",date:"25-Sep-2025",type:"NSP",attendees:35,salesperson:null,reported:true,kols:[]},
{id:83,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"September",date:"30-Sept-2025",type:"NSP",attendees:43,salesperson:null,reported:true,kols:[]},
{id:84,therapy:"Opthal",event:"Bayer I-Sight meeting (7:30 pm)",month:"September",date:"30-Sept-2025",type:"NSP",attendees:43,salesperson:null,reported:true,kols:[]},
{id:85,therapy:"Onco",event:"Prostate Cancer CME",month:"September",date:"30-Sep-2025",type:"NSP",attendees:37,salesperson:null,reported:true,kols:[]},
{id:86,therapy:"Onco",event:"Prostate Cancer CME",month:"October",date:"9-Oct-2025",type:"NSP",attendees:64,salesperson:null,reported:true,kols:[]},
{id:87,therapy:"Onco",event:"Prostate Cancer CME (Only Link)",month:"October",date:"10-Oct-2025",type:"NSP",attendees:56,salesperson:null,reported:true,kols:[]},
{id:88,therapy:"Opthal",event:"Bayer I-Sight meeting (8:00 pm)",month:"October",date:"11-Oct-2025",type:"NSP",attendees:30,salesperson:null,reported:true,kols:[]},
{id:89,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"October",date:"14-Oct-2025",type:"NSP",attendees:27,salesperson:null,reported:true,kols:[]},
{id:90,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"October",date:"16-Oct-2025",type:"NSP",attendees:51,salesperson:null,reported:true,kols:[]},
{id:91,therapy:"Onco",event:"Prostate Cancer CME (Only Link)",month:"October",date:"17-Oct-2025",type:"NSP",attendees:46,salesperson:null,reported:true,kols:[]},
{id:92,therapy:"Onco",event:"Prostate Cancer CME",month:"October",date:"24-Oct-2025",type:"NSP",attendees:45,salesperson:null,reported:true,kols:[]},
{id:93,therapy:"Opthal",event:"Bayer I-Sight meeting (Phygital)",month:"October",date:"27-Oct-2025",type:"ISP",attendees:20,salesperson:null,reported:true,kols:[]},
{id:94,therapy:"Onco",event:"Prostate Cancer CME (Only Link)",month:"October",date:"27-Oct-2025",type:"NSP",attendees:28,salesperson:null,reported:true,kols:[]},
{id:95,therapy:"Opthal",event:"Bayer I-Sight meeting (Phygital)",month:"October",date:"28-Oct-2025",type:"ISP",attendees:20,salesperson:null,reported:true,kols:[]},
{id:96,therapy:"Opthal",event:"Bayer I-Sight meeting (Phygital)",month:"October",date:"29-Oct-2025",type:"ISP",attendees:20,salesperson:null,reported:true,kols:[]},
{id:97,therapy:"Onco",event:"Prostate Cancer CME",month:"October",date:"30-Oct-2025",type:"NSP",attendees:61,salesperson:null,reported:true,kols:[]},
{id:98,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"October",date:"30-Oct-2025",type:"NSP",attendees:35,salesperson:null,reported:true,kols:[]},
{id:99,therapy:"Onco",event:"Prostate Cancer CME",month:"October",date:"31-Oct-2025",type:"NSP",attendees:61,salesperson:null,reported:true,kols:[]},
{id:100,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"November",date:"6-Nov-2025",type:"NSP",attendees:47,salesperson:null,reported:true,kols:[]},
{id:101,therapy:"Onco",event:"Prostate Cancer CME",month:"November",date:"11-Nov-2025",type:"NSP",attendees:67,salesperson:null,reported:true,kols:[]},
{id:102,therapy:"Onco",event:"Prostate Cancer CME",month:"November",date:"12-Nov-2025",type:"NSP",attendees:30,salesperson:null,reported:true,kols:[]},
{id:103,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"November",date:"13-Nov-2025",type:"NSP",attendees:36,salesperson:null,reported:true,kols:[]},
{id:104,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"November",date:"19-Nov-2025",type:"NSP",attendees:52,salesperson:null,reported:true,kols:[]},
{id:105,therapy:"Opthal",event:"Bayer I-Sight meeting (7:30 pm)",month:"November",date:"19-Nov-2025",type:"NSP",attendees:47,salesperson:null,reported:true,kols:[]},
{id:106,therapy:"Onco",event:"Prostate Cancer CME",month:"November",date:"20-Nov-2025",type:"NSP",attendees:75,salesperson:null,reported:true,kols:[]},
{id:107,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"November",date:"22-Nov-2025",type:"NSP",attendees:19,salesperson:null,reported:true,kols:[]},
{id:108,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"November",date:"26-Nov-2025",type:"NSP",attendees:37,salesperson:null,reported:true,kols:[]},
{id:109,therapy:"Onco",event:"Prostate Cancer CME",month:"November",date:"27-Nov-2025",type:"NSP",attendees:49,salesperson:null,reported:true,kols:[]},
{id:110,therapy:"Onco",event:"Prostate Cancer CME",month:"November",date:"28-Nov-2025",type:"NSP",attendees:48,salesperson:null,reported:true,kols:[]},
{id:111,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"November",date:"28-Nov-2025",type:"NSP",attendees:31,salesperson:null,reported:true,kols:[]},
{id:112,therapy:"Onco",event:"Prostate Cancer CME",month:"December",date:"2-Dec-2025",type:"NSP",attendees:45,salesperson:null,reported:true,kols:["Dr. Suman Meyur","Dr. Nihanthy DS","Dr. Shasanka Sekhar Das"]},
{id:113,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"December",date:"2-Dec-2025",type:"NSP",attendees:47,salesperson:null,reported:true,kols:["Dr. Nimesh Jain","Dr. Bhavik Panchal"]},
{id:114,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"December",date:"3-Dec-2025",type:"NSP",attendees:88,salesperson:null,reported:true,kols:["Dr Anil Patil","Dr Prasad Kamat","Dr Urmil Shah"]},
{id:115,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"December",date:"5-Dec-2025",type:"NSP",attendees:45,salesperson:null,reported:true,kols:["Dr Pratik Mahajan"]},
{id:116,therapy:"Onco",event:"Prostate Cancer CME",month:"December",date:"6-Dec-2025",type:"Advisory",attendees:23,salesperson:null,reported:true,kols:[]},
{id:117,therapy:"Onco",event:"Prostate Cancer CME",month:"December",date:"11-Dec-2025",type:"NSP",attendees:68,salesperson:null,reported:true,kols:["Dr R Manikandan","Dr Bhavya S Kumar","Dr Rachana Chennameni"]},
{id:118,therapy:"Onco",event:"Prostate Cancer CME",month:"December",date:"13-Dec-2025",type:"ISP",attendees:null,salesperson:null,reported:false,kols:["Professor Dr. Amit Bahl"]},
{id:119,therapy:"Onco",event:"Prostate Cancer CME (8-9)",month:"December",date:"13-Dec-2025",type:"ISP",attendees:null,salesperson:null,reported:false,kols:["Professor Dr. Amit Bahl"]},
{id:120,therapy:"Onco",event:"Prostate Cancer CME (1:45pm-3:45 pm) Banglore",month:"December",date:"13-Dec-2025",type:"ISP",attendees:null,salesperson:null,reported:false,kols:["Professor Dr. Amit Bahl"]},
{id:121,therapy:"Onco",event:"Prostate Cancer CME (8:00 pm-9:30 pm) Bhopal",month:"December",date:"13-Dec-2025",type:"ISP",attendees:null,salesperson:null,reported:false,kols:["Professor Dr. Amit Bahl"]},
{id:122,therapy:"Onco",event:"Prostate Cancer CME (7:30 pm onwards) Thiruvantampuram",month:"December",date:"13-Dec-2025",type:"ISP",attendees:null,salesperson:null,reported:false,kols:["Professor Dr. Amit Bahl"]},
{id:123,therapy:"Opthal",event:"Bayer I-Sight meeting (7:30 pm)",month:"December",date:"13-Dec-2025",type:"NSP",attendees:25,salesperson:null,reported:true,kols:["Dr. Shradha Pattnaik","Dr. Saumendu Mohanty"]},
{id:124,therapy:"Onco",event:"Prostate Cancer CME (8:00 pm) Guwahati",month:"December",date:"13-Dec-2025",type:"ISP",attendees:null,salesperson:null,reported:false,kols:["Professor Dr. Amit Bahl"]},
{id:125,therapy:"Onco",event:"Prostate Cancer CME (8:00 pm) New Delhi",month:"December",date:"13-Dec-2025",type:"ISP",attendees:null,salesperson:null,reported:false,kols:["Professor Dr. Amit Bahl"]},
{id:126,therapy:"Onco",event:"Prostate Cancer CME (8:00 pm) Lucknow",month:"December",date:"13-Dec-2025",type:"ISP",attendees:null,salesperson:null,reported:false,kols:["Professor Dr. Amit Bahl"]},
{id:127,therapy:"Onco",event:"Prostate Cancer CME (1:15 to 3:00 PM) Coimbatore",month:"December",date:"13-Dec-2025",type:"ISP",attendees:null,salesperson:null,reported:false,kols:["Professor Dr. Amit Bahl"]},
{id:128,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"December",date:"15-Dec-2025",type:"NSP",attendees:50,salesperson:null,reported:true,kols:[]},
{id:129,therapy:"Opthal",event:"Bayer I-Sight meeting (8:30 pm)",month:"December",date:"15-Dec-2025",type:"NSP",attendees:44,salesperson:null,reported:true,kols:["Dr. Vedang Shah","Dr. Shouvick Dan"]},
{id:130,therapy:"Onco",event:"Prostate Cancer CME",month:"December",date:"16-Dec-2025",type:"NSP",attendees:28,salesperson:null,reported:true,kols:[]},
{id:131,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"December",date:"19-Dec-2025",type:"NSP",attendees:53,salesperson:null,reported:true,kols:[]},
{id:132,therapy:"Onco",event:"Prostate Cancer CME",month:"December",date:"20-Dec-2025",type:"ISP",attendees:54,salesperson:null,reported:true,kols:[]},
{id:133,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"December",date:"20-Dec-2025",type:"NSP",attendees:57,salesperson:null,reported:true,kols:[]},
{id:134,therapy:"Onco",event:"Prostate Cancer CME (Only Link)",month:"December",date:"22-Dec-2025",type:"NSP",attendees:29,salesperson:null,reported:true,kols:[]},
{id:135,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"December",date:"23-Dec-2025",type:"NSP",attendees:55,salesperson:null,reported:true,kols:[]},
{id:136,therapy:"Onco",event:"Prostate Cancer CME (Only Link)",month:"December",date:"23-Dec-2025",type:"NSP",attendees:33,salesperson:null,reported:true,kols:[]},
{id:137,therapy:"Onco",event:"Prostate Cancer CME (Only Link)",month:"December",date:"24-Dec-2025",type:"NSP",attendees:26,salesperson:null,reported:true,kols:[]},
{id:138,therapy:"Onco",event:"Prostate Cancer CME (8 pm)",month:"December",date:"26-Dec-2025",type:"NSP",attendees:47,salesperson:null,reported:true,kols:[]},
{id:139,therapy:"Onco",event:"Prostate Cancer CME",month:"December",date:"27-Dec-2025",type:"NSP",attendees:47,salesperson:null,reported:true,kols:[]},
{id:140,therapy:"Onco",event:"Prostate Cancer CME",month:"January",date:"23-Jan-2026",type:"NSP",attendees:33,salesperson:null,reported:true,kols:["Dr. Murtaza Bohra"]},
{id:141,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"January",date:"24-Jan-2026",type:"NSP",attendees:25,salesperson:null,reported:true,kols:["Dr. Sree Ram Charan"]},
{id:142,therapy:"Onco",event:"Prostate Cancer CME",month:"January",date:"24-Jan-2026",type:"NSP",attendees:41,salesperson:null,reported:true,kols:["Dr. Uma Shankar Kutum","Dr. Smita Kumari"]},
{id:143,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"January",date:"27-Jan-2026",type:"NSP",attendees:23,salesperson:null,reported:true,kols:[]},
{id:144,therapy:"Onco",event:"Prostate Cancer CME (7:30 PM)",month:"January",date:"29-Jan-2026",type:"NSP",attendees:26,salesperson:null,reported:true,kols:["Dr. Anup Toshniwal"]},
{id:145,therapy:"Onco",event:"Prostate Cancer CME (8 PM)",month:"January",date:"29-Jan-2026",type:"NSP",attendees:70,salesperson:null,reported:true,kols:["Dr. Abhishek Anand","Dr. Gaurav Kumar","Dr. Debapriya Mondal"]},
{id:146,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"January",date:"29-Jan-2026",type:"NSP",attendees:38,salesperson:null,reported:true,kols:["Dr. Eesh Nigam","Dr. Somnath Chakraborty"]},
{id:147,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"January",date:"31-Jan-2026",type:"NSP",attendees:48,salesperson:null,reported:true,kols:["Dr. Stalin Bala","Dr. Y Rajani Priya","Dr. P Venkateswara Rao"]},
{id:148,therapy:"Opthal",event:"Bayer I-Sight meeting",month:"February",date:"2-Feb-2026",type:"NSP",attendees:39,salesperson:null,reported:true,kols:["Dr Carthikeyan S.M.","Dr Karthikeyan S"]},
{id:149,therapy:"Onco",event:"Internal Event",month:"February",date:"4-Feb-2026",type:"NSP",attendees:null,salesperson:null,reported:true,kols:[]},
{id:150,therapy:"Opthal",event:"Bayer I-Sight meeting, 8:30 PM",month:"February",date:"7-Feb-2026",type:"NSP",attendees:34,salesperson:null,reported:true,kols:["Dr. Swakshyar Saumya Pal","Dr. Jaydeep Majumder"]},
{id:151,therapy:"Onco",event:"Prostate Cancer CME (7:30 PM)",month:"February",date:"7-Feb-2026",type:"NSP",attendees:54,salesperson:null,reported:true,kols:["Dr. C Santosh Kumar","Dr. G Vamshi Krishna Reddy","Dr. Thota Narender Kumar"]},
{id:152,therapy:"Onco",event:"Prostate Cancer CME (8:00 PM)",month:"February",date:"7-Feb-2026",type:"NSP",attendees:57,salesperson:null,reported:true,kols:["Dr. Naresh Jadhav","Dr. Chandrakanth MV","Dr. K. Sanath"]},
{id:153,therapy:"Onco",event:"Prostate Cancer CME (Only Link)",month:"February",date:"11-Feb-2026",type:"NSP",attendees:64,salesperson:null,reported:true,kols:["Dr P Satya Dattatreya","Dr M Ravi Krishna","Dr Vindhya Vasini"]},
{id:154,therapy:"Onco",event:"Prostate Cancer CME",month:"February",date:"17-Feb-2026",type:"NSP",attendees:54,salesperson:null,reported:true,kols:["Dr. Rachana Chennamaneni","Dr. Nishith Vaddeboina","Dr. Namratha Sai Reddy"]},
{id:155,therapy:"Onco",event:"Prostate Cancer CME",month:"February",date:"18-Feb-2026",type:"NSP",attendees:45,salesperson:null,reported:true,kols:[]},
{id:156,therapy:"Onco",event:"Ad Board Meeting link",month:"February",date:"21-Feb-2026",type:"Advisory",attendees:null,salesperson:null,reported:false,kols:[]},
{id:157,therapy:"Onco",event:"Bayer Oncology meeting 7:00 PM (Arumugam)",month:"February",date:"25-Feb-2026",type:"NSP",attendees:42,salesperson:"Arumugam",reported:true,kols:["Dr PN Sathiyamoorthy","Dr Prabagar M"]},
{id:158,therapy:"Onco",event:"Bayer Oncology meeting 7:30 PM (Mr. Sandeep)",month:"February",date:"25-Feb-2026",type:"NSP",attendees:42,salesperson:"Sandeep",reported:true,kols:["Dr. Shasanka Sekhar Das","Dr. Shyny Reddy","Dr. N Thejeswar"]},
{id:159,therapy:"Opthal",event:"Bayer I-Sight meeting, 7:00 PM (Mr. Anil Kumar)",month:"February",date:"26-Feb-2026",type:"NSP",attendees:25,salesperson:"Anil Kumar",reported:true,kols:[]},
{id:160,therapy:"Onco",event:"Prostate Cancer CME (8:00 PM) (Mr. Vinoth)",month:"February",date:"26-Feb-2026",type:"NSP",attendees:37,salesperson:"Vinoth",reported:true,kols:["Dr Mathews Jose","Dr Nikhil Haridas","Dr Stalin Bala"]},
{id:161,therapy:"Opthal",event:"Bayer I-Sight meeting, 8:30 PM",month:"February",date:"20-Feb-2026",type:"NSP",attendees:53,salesperson:null,reported:true,kols:["Dr. AMAN CHAUDHARY"]},
{id:162,therapy:"Opthal",event:"Bayer I-Sight meeting, 8:30 PM",month:"February",date:"23-Feb-2026",type:"NSP",attendees:40,salesperson:null,reported:true,kols:[]},
{id:163,therapy:"Opthal",event:"Bayer I-Sight meeting, 8:30 PM",month:"February",date:"24-Feb-2026",type:"NSP",attendees:30,salesperson:null,reported:true,kols:[]},
{id:164,therapy:"Onco",event:"Bayer Oncology meeting, 8:00 PM",month:"February",date:"24-Feb-2026",type:"NSP",attendees:51,salesperson:null,reported:true,kols:[]},
{id:165,therapy:"Opthal",event:"Bayer I-Sight meeting, 7:00 PM (Anil Kumar)",month:"February",date:"25-Feb-2026",type:"NSP",attendees:25,salesperson:"Anil Kumar",reported:true,kols:["Dr. Sree Ram Charan"]},
{id:166,therapy:"Onco",event:"Bayer Oncology meeting, 7:00 PM",month:"February",date:"20-Feb-2026",type:"NSP",attendees:31,salesperson:null,reported:true,kols:["DR. AMAN CHAUDHARY"]},
{id:167,therapy:"Opthal",event:"Bayer I-Sight meeting, 7:00 PM",month:"February",date:"23-Feb-2026",type:"NSP",attendees:57,salesperson:null,reported:true,kols:["Dr Aditi Gupta","Dr Saurabh Arora","Dr. Vidhi Bajpai"]},
{id:168,therapy:"Onco",event:"Bayer Oncology meeting (7:30 PM) (Mr. Sandeep Kumar)",month:"February",date:"24-Feb-2026",type:"NSP",attendees:50,salesperson:"Sandeep Kumar",reported:true,kols:["Dr. P Krishna Chaitanya","Dr. Alapati Neeharika","Dr. Kota Kishore Kumar"]},
{id:169,therapy:"Onco",event:"Bayer Oncology meeting, 7:00 PM (Tejraj Vaidya)",month:"February",date:"25-Feb-2026",type:"NSP",attendees:24,salesperson:"Tejraj Vaidya",reported:true,kols:["Dr. Pratik Patil"]},
{id:170,therapy:"Onco",event:"Bayer Oncology meeting,, 7:30 PM (Mr. Sandeep Kumar)",month:"February",date:"25-Feb-2026",type:"NSP",attendees:61,salesperson:"Sandeep Kumar",reported:true,kols:["Dr. Shasanka Sekhar Das","Dr. Shyny Reddy","Dr. N Thejeswar"]},
{id:171,therapy:"Opthal",event:"Bayer I-Sight meeting, 8:00 PM (Mr. Sushil)",month:"February",date:"25-Feb-2026",type:"NSP",attendees:39,salesperson:"Sushil",reported:true,kols:["Dr. Sonal Lakdawala Jadhav","Dr. Ruchi Vala"]},
{id:172,therapy:"Onco",event:"Bayer Oncology meeting,, 7:00 PM (Padmo)",month:"February",date:"26-Feb-2026",type:"NSP",attendees:47,salesperson:"Padmo",reported:true,kols:["Dr. Duncan Khanikar","Dr. Venkata Pradeep Babu Koyyala"]},
{id:173,therapy:"Onco",event:"Bayer Oncology meeting, 7:30 PM (Mr. Sandeep Kumar)",month:"February",date:"27-Feb-2026",type:"NSP",attendees:53,salesperson:"Sandeep Kumar",reported:true,kols:["Dr. G Sadashivudu","Dr. G Muralidhar","Dr. Y Rajani Priya"]},
{id:174,therapy:"Onco",event:"Bayer Advisory Oncology",month:"February",date:"27-Feb-2026",type:"Advisory",attendees:null,salesperson:null,reported:true,kols:[]},
{id:175,therapy:"Onco",event:"Bayer Oncology meeting, 7:30 PM (Mr. Arnab)",month:"February",date:"27-Feb-2026",type:"NSP",attendees:43,salesperson:"Arnab",reported:true,kols:["Dr. (Prof.) Kushal Gupta","Dr. Poulami Basu"]},
{id:176,therapy:"Onco",event:"Bayer Oncology meeting (Mr. Sandeep Kumar)",month:"February",date:"28-Feb-2026",type:"NSP",attendees:56,salesperson:"Sandeep Kumar",reported:true,kols:["Dr. Sravan Kumar Dubasi","Dr. Santosh Kumar Chellapuram","Dr. Sravan Kumar Chinthala"]},
{id:177,therapy:"Onco",event:"Bayer Oncology meeting, 8PM (Sagnik Tribedi)",month:"March",date:"2-Mar-2026",type:"NSP",attendees:65,salesperson:"Sagnik Tribedi",reported:true,kols:["Dr. Chandrakanth MV","Dr. Gunjesh Kumar Singh","Dr. Amit Kumar"]},
{id:178,therapy:"Opthal",event:"Bayer I-sight meeting, 7:30pm (Nrup Patel)",month:"March",date:"2-Mar-2026",type:"NSP",attendees:51,salesperson:"Nrup Patel",reported:true,kols:["Dr. Dipak Soni","Dr. Kaushal Kishor Sharma"]},
{id:179,therapy:"Opthal",event:"Bayer I-sight meeting, 8:30pm (Hrishikesh Mondal)",month:"March",date:"5-Mar-2026",type:"NSP",attendees:39,salesperson:"Hrishikesh Mondal",reported:true,kols:["Dr. Rupak Roy","Dr. Krishna Kanta Roy"]},
{id:180,therapy:"Onco",event:"Bayer Oncology Meeting 8 pm (dipak)",month:"March",date:"6-Mar-2026",type:"NSP",attendees:34,salesperson:"Deepak",reported:true,kols:["Dr Satvik Khaddar"]},
{id:181,therapy:"Onco",event:"Bayer Oncology Meeting, 7:00 pm (Rajshekar)",month:"March",date:"11-Mar-2026",type:"NSP",attendees:51,salesperson:"Rajshekar",reported:true,kols:["Dr Vishwajeeth K Pai","Dr MR Kaushik"]},
{id:182,therapy:"Onco",event:"Bayer Oncology Meeting, 7:00 pm (Arnab)",month:"March",date:"10-Mar-2026",type:"NSP",attendees:52,salesperson:"Arnab",reported:true,kols:["Dr. Suman Meyur","Dr. Vivek Agarwala"]},
{id:183,therapy:"Opthal",event:"Bayer I-Sight Meeting, 7:00 pm (Prateek)",month:"March",date:"10-Mar-2026",type:"NSP",attendees:46,salesperson:"Prateek",reported:true,kols:["Dr Mihir Trivedi","Dr Sonal Paliwal"]},
{id:184,therapy:"Onco",event:"Bayer Oncology Meeting, 8:00 pm (Sagnik)",month:"March",date:"19-Mar-2026",type:"NSP",attendees:51,salesperson:"Sagnik Tribedi",reported:true,kols:["Dr Poulami Basu","Dr Chandrashekhar Prasad Singh","Dr Abhijit Das"]},
{id:185,therapy:"Onco",event:"Bayer Oncology Meeting, 8:00 pm (Arnab)",month:"March",date:"17-Mar-2026",type:"NSP",attendees:51,salesperson:"Arnab",reported:true,kols:["Dr Chanchal Goswami","Dr Chinmaya Kumar Pani"]},
{id:186,therapy:"Onco",event:"Bayer Oncology Meeting, 8:00 pm (Padmo)",month:"March",date:"13-Mar-2026",type:"NSP",attendees:53,salesperson:"Padmo",reported:true,kols:["Dr. Naresh Jadhav","Dr. Anupam Mahanta","Dr. Madhuchanda Kar"]},
{id:187,therapy:"Onco",event:"Bayer Oncology Meeting, 8:30 pm (Sourav)",month:"March",date:"18-Mar-2026",type:"NSP",attendees:49,salesperson:"Sourav",reported:true,kols:["Dr Debmalya Das","Dr Akashdeep"]},
{id:188,therapy:"Onco",event:"Bayer Oncology Meeting (Mr.Sandeep)",month:"March",date:"21-Mar-2026",type:"NSP",attendees:60,salesperson:"Sandeep Kumar",reported:true,kols:["Dr P Krishna Chaitanya","Dr KV Krishnamani","Dr Venugopal Arroju"]},
{id:189,therapy:"Onco",event:"Bayer Oncology Meeting, 7:30 pm (Mr. Arnab)",month:"March",date:"25-Mar-2026",type:"NSP",attendees:54,salesperson:"Arnab",reported:true,kols:["Dr. Prof Ghanashyam Biswas","Dr. Rajiv Lochan Jena","Dr. Santosh Kumar C"]},
{id:190,therapy:"Onco",event:"Bayer Oncology Meeting (Mr. Sandeep) 7.30 pm",month:"March",date:"26-Mar-2026",type:"NSP",attendees:57,salesperson:"Sandeep Kumar",reported:true,kols:["Dr P Nageswara Reddy","Dr K Meher Lakshmi","Dr P Venkateswara Rao"]},
{id:191,therapy:"Opthal",event:"Bayer I Sight Meeting (Mr. Dinesh)",month:"March",date:"26-Mar-2026",type:"NSP",attendees:47,salesperson:"Dinesh",reported:true,kols:["Dr Vinay Prasad","Dr Sugandha Goel"]},
{id:192,therapy:"Opthal",event:"Bayer I Sight Meeting (Mr. Hrishikesh)",month:"March",date:"28-Mar-2026",type:"NSP",attendees:28,salesperson:"Hrishikesh Mondal",reported:true,kols:["Dr. Apurba Adhikari"]},
{id:193,therapy:"Onco",event:"Bayer Onco Meeting (Mr Sandeep)",month:"March",date:"28-Mar-2026",type:"NSP",attendees:50,salesperson:"Sandeep Kumar",reported:true,kols:["Dr Ramesh Reddy","Dr Madhav Danthala","Dr Nithin Raj"]},
{id:194,therapy:"Opthal",event:"Bayer I Sight Meeting (Mr. Abhishek)",month:"March",date:"30-Mar-2026",type:"NSP",attendees:53,salesperson:"Abhishek",reported:true,kols:["Dr. Arnab Das","Dr. Vedang Shah"]},
{id:195,therapy:"Onco",event:"Bayer Oncology Meeting (Deepak)",month:"March",date:"31-Mar-2026",type:"NSP",attendees:30,salesperson:"Deepak",reported:true,kols:["Dr Vijay Bhargava"]},
{id:196,therapy:"Onco",event:"Bayer Oncology Meeting (Padmo)",month:"March",date:"31-Mar-2026",type:"NSP",attendees:60,salesperson:"Padmo",reported:true,kols:["Dr. Kakoli Medhi","Dr. Hitesh Deka","Dr. Palanki Satya Dattatreya"]},
{id:197,therapy:"Onco",event:"Bayer Oncology Meeting, 8 pm (Krutika)",month:"April",date:"1-Apr-2026",type:"NSP",attendees:30,salesperson:"Krutika",reported:true,kols:["Dr Bharat Bhosale"]},
{id:198,therapy:"Onco",event:"Bayer Oncology Meeting, 7 pm (Krutika)",month:"April",date:"2-Apr-2026",type:"NSP",attendees:23,salesperson:"Krutika",reported:true,kols:["Dr Parth Ganatra"]},
{id:199,therapy:"Onco",event:"Bayer Oncology Meeting, 8 pm (Sagnik)",month:"April",date:"2-Apr-2026",type:"NSP",attendees:45,salesperson:"Sagnik Tribedi",reported:true,kols:["Dr. Debapriya Mondal","Dr. Debanti Banerjee"]},
{id:200,therapy:"Opthal",event:"Bayer I-Sight Meeting (Hrishikesh)",month:"April",date:"7-Apr-2026",type:"NSP",attendees:52,salesperson:"Hrishikesh Mondal",reported:true,kols:["Dr. Pranab Das","Dr. Antarlin Ghosal","Dr. Souvick Dan"]},
{id:201,therapy:"Onco",event:"Prostate Cancer CME",month:"April",date:"14-Apr-2026",type:"NSP",attendees:67,salesperson:null,reported:true,kols:["Dr. P N Mohapatra","Dr. Shasanka Sekhar Das"]},
{id:202,therapy:"Opthal",event:"Bayer I-Sight Meeting (8:30 pm)",month:"April",date:"15-Apr-2026",type:"NSP",attendees:49,salesperson:null,reported:true,kols:["Dr. Sangeeta Roy","Dr. Rupak Roy","Dr. Zahir Abbas"]},
{id:203,therapy:"Onco",event:"Prostate Cancer CME",month:"April",date:"16-Apr-2026",type:"NSP",attendees:53,salesperson:null,reported:true,kols:["Dr Ramya A","Dr Gayatri Gopan","Dr Dilip Harindran"]},
{id:204,therapy:"Onco",event:"Prostate Cancer CME (Only Link) 7:30 pm",month:"April",date:"17-Apr-2026",type:"NSP",attendees:27,salesperson:null,reported:true,kols:["DR. TUSHAR PATIL"]},
{id:205,therapy:"Opthal",event:"Bayer I-Sight Meeting (6:00 pm) Offline event",month:"April",date:"18-Apr-2026",type:"NSP",attendees:null,salesperson:null,reported:false,kols:["Dr. Aniruddha Mahindrakar"]},
{id:206,therapy:"Onco",event:"Prostate Cancer CME (Only Link)",month:"April",date:"20-Apr-2026",type:"NSP",attendees:40,salesperson:null,reported:true,kols:["Dr Poulami Basu","Dr Tanmoy Kumar Mondal"]},
{id:207,therapy:"Onco",event:"Prostate Cancer CME",month:"April",date:"21-Apr-2026",type:"NSP",attendees:49,salesperson:null,reported:true,kols:["Dr SS NIRNI"]},
{id:208,therapy:"Onco",event:"Prostate Cancer CME (7:30 pm) Tejraj",month:"April",date:"21-Apr-2026",type:"NSP",attendees:30,salesperson:"Tejraj",reported:true,kols:["DR. ANUP TOSHNIWAL"]},
{id:209,therapy:"Opthal",event:"Bayer I-Sight Meeting (8:00 pm)",month:"April",date:"21-Apr-2026",type:"NSP",attendees:77,salesperson:null,reported:true,kols:["Dr. Pooja Sinha","Dr. Chitaranjan Mishra","Dr. Subhendu Boral"]},
{id:210,therapy:"Opthal",event:"Bayer I-Sight Meeting (8:30 pm)",month:"April",date:"22-Apr-2026",type:"NSP",attendees:43,salesperson:null,reported:true,kols:["Dr. Surendra Prakash","Dr. Atish Kumar Pradhan"]},
{id:211,therapy:"Onco",event:"Prostate Cancer CME (7:00 pm)",month:"April",date:"23-Apr-2026",type:"NSP",attendees:74,salesperson:null,reported:true,kols:["Dr P S Dattatreya","Dr Arun V","Dr Rajiv Gandhi"]},
{id:212,therapy:"Onco",event:"Prostate Cancer CME (8:00 pm)",month:"April",date:"23-Apr-2026",type:"NSP",attendees:43,salesperson:null,reported:true,kols:["Dr. Saptarshi Ghosh","Dr. MV Chandrakanth"]},
{id:213,therapy:"Onco",event:"Prostate Cancer CME (7:00 pm) Vinoth",month:"April",date:"24-Apr-2026",type:"NSP",attendees:53,salesperson:"Vinoth",reported:true,kols:["Dr. Suman Meyur","Dr. Madhuchanda Kar"]},
{id:214,therapy:"Onco",event:"Prostate Cancer CME (7:00 pm) Arnab",month:"April",date:"24-Apr-2026",type:"NSP",attendees:47,salesperson:"Arnab",reported:true,kols:["Dr Krishnanunni V A","Dr Saphalta Baghmar","Dr Rudresha A H"]},
{id:215,therapy:"Onco",event:"Prostate Cancer CME (6:30 pm) Arumugam",month:"April",date:"24-Apr-2026",type:"NSP",attendees:28,salesperson:"Arumugam",reported:true,kols:[]},
{id:216,therapy:"Opthal",event:"Bayer I-Sight Meeting (8:30 pm) Dhrubajit",month:"April",date:"24-Apr-2026",type:"NSP",attendees:38,salesperson:"Dhrubajit",reported:true,kols:["Dr. Manabjyoti Barman","Dr. Debdulal Chakraborty"]},
{id:217,therapy:"Onco",event:"Prostate Cancer CME (8:00 pm) Padmo",month:"April",date:"25-Apr-2026",type:"NSP",attendees:43,salesperson:"Padmo",reported:true,kols:["Dr. Naresh Jadhav","Dr. Umesh Das"]},
{id:218,therapy:"Opthal",event:"Bayer I-Sight Meeting (8:30 pm)",month:"April",date:"27-Apr-2026",type:"NSP",attendees:42,salesperson:null,reported:true,kols:["Dr. Dinesh Rungta","Dr. Subhadip Sarkar"]},
{id:219,therapy:"Onco",event:"Prostate Cancer CME (8:00 pm) Arnab",month:"April",date:"28-Apr-2026",type:"NSP",attendees:40,salesperson:"Arnab",reported:true,kols:["Dr Sudeep Das","Dr Pradip Kumar Mondal"]},
{id:220,therapy:"Onco",event:"Prostate Cancer CME (8:00 pm) Sagnik",month:"April",date:"28-Apr-2026",type:"NSP",attendees:26,salesperson:"Sagnik",reported:true,kols:["Dr. Satish Sharma","Dr. Parag Roy"]},
{id:221,therapy:"Opthal",event:"Bayer I-Sight Meeting (8:00 pm) Dinesh Mehta",month:"April",date:"28-Apr-2026",type:"NSP",attendees:130,salesperson:"Dinesh Mehta",reported:true,kols:["Dr. Abhishek Sachdeva","Dr. Suraj Bajwa"]},
{id:222,therapy:"Onco",event:"Prostate Cancer CME (8:00 pm) Arnab",month:"April",date:"29-Apr-2026",type:"NSP",attendees:52,salesperson:"Arnab",reported:true,kols:["Dr. Kushal Gupta","Dr. Abhishek Anand"]},
{id:223,therapy:"Onco",event:"Prostate Cancer CME (8:00 pm) Mr. Arnab",month:"April",date:"30-Apr-2026",type:"NSP",attendees:37,salesperson:"Arnab",reported:true,kols:["Dr. Rajiv Lochan Jena","Dr. Chanchal Goswami"]},
{id:224,therapy:"Onco",event:"Prostate Cancer CME (7:00 pm) Mr. Arnab",month:"April",date:"30-Apr-2026",type:"NSP",attendees:22,salesperson:"Arnab",reported:true,kols:["Dr Nihanthy DS"]},
{id:225,therapy:"Opthal",event:"Bayer I-Sight Meeting (7:00 pm) Anil",month:"April",date:"30-Apr-2026",type:"NSP",attendees:25,salesperson:"Anil",reported:true,kols:["Dr. Sree Ram Charan"]},
{id:226,therapy:"Opthal",event:"Bayer I-Sight Meeting (8:30 pm) Hrishikesh Mondal",month:"April",date:"30-Apr-2026",type:"NSP",attendees:39,salesperson:"Hrishikesh Mondal",reported:true,kols:["Dr. Arnab Das","Dr. Souvik Sen"]},
{id:227,therapy:"Onco",event:"Prostate Cancer CME (7:30 pm) Sandeep",month:"April",date:"30-Apr-2026",type:"NSP",attendees:63,salesperson:"Sandeep",reported:true,kols:["Dr. M Ravi Krishna","Dr. Sravan Kumar Dubasi","Dr G Lakshmi Deepthi"]},
{id:228,therapy:"Opthal",event:"Bayer I-sight Meeting 7:30 pm (Mr. Dinesh)",month:"April",date:"30-Apr-2026",type:"NSP",attendees:86,salesperson:"Dinesh",reported:true,kols:["Dr. Anshu Arora","Dr. Supreet Juneja","Dr. Anuj Sharma"]},
{id:229,therapy:"Opthal",event:"Bayer I-Sight Meeting (8:00 pm) Dinesh Mehta",month:"May",date:"2-May-2026",type:"NSP",attendees:77,salesperson:"Dinesh Mehta",reported:true,kols:["Dr. Gurwinder Kaur","Dr. Kanwaljeet Kaur","Dr. Pallavi Singh"]},
{id:230,therapy:"Onco",event:"Prostate Cancer CME (7:00 pm) Arumugam Only Link",month:"May",date:"7-May-2026",type:"NSP",attendees:36,salesperson:"Arumugam",reported:true,kols:["Dr Carthikeyan"]},
{id:231,therapy:"Opthal",event:"Bayer I-Sight Meeting (8:30 pm) Hrishikesh Mondal",month:"May",date:"9-May-2026",type:"NSP",attendees:38,salesperson:"Hrishikesh Mondal",reported:true,kols:["Dr. Soumen Mondal","Dr. Jaydeep Majumder"]},
{id:232,therapy:"Onco",event:"ISP Prime Meet 2026",month:"May",date:"9-May-2026",type:"ISP",attendees:null,salesperson:null,reported:true,kols:["Prof. Dr. Maha Hussain"]},
{id:233,therapy:"Opthal",event:"Bayer I-Sight Meeting (7:30 pm) Dinesh",month:"May",date:"10-May-2026",type:"NSP",attendees:47,salesperson:"Dinesh",reported:true,kols:["Dr. S N Jha","Dr. Anil Solanki","Dr. Prashant Jain"]},
{id:234,therapy:"Onco",event:"Bayer Onco Meeting (8:00 pm) Arnab",month:"May",date:"11-May-2026",type:"NSP",attendees:39,salesperson:"Arnab",reported:true,kols:["Dr. Ghanashyam Biswas"]},
{id:235,therapy:"Onco",event:"Bayer Onco Meeting (8:00 pm) Sagnik",month:"May",date:"12-May-2026",type:"NSP",attendees:44,salesperson:"Sagnik",reported:true,kols:["Dr. Debapriya Mondal","Dr. Animesh Saha"]},
{id:236,therapy:"Onco",event:"Bayer Onco Meeting (8:00 pm) Padmo",month:"May",date:"12-May-2026",type:"NSP",attendees:37,salesperson:"Padmo",reported:true,kols:["Dr. Duncan Khanikar","Dr. Smita Kumari"]},
{id:237,therapy:"Onco",event:"Bayer Onco Meeting (8:00 pm) Arnab",month:"May",date:"14-May-2026",type:"NSP",attendees:36,salesperson:"Arnab",reported:true,kols:["Dr Chinmaya Kumar Pani"]},
{id:238,therapy:"Opthal",event:"Bayer I-Sight Meeting (8:00 pm) Prateek",month:"May",date:"15-May-2026",type:"NSP",attendees:44,salesperson:"Prateek",reported:true,kols:["Dr Shachi Joshi","Dr Mayur Rokdey"]},
{id:239,therapy:"Onco",event:"Prostate Cancer CME (8:00 pm) Arnab",month:"May",date:"15-May-2026",type:"NSP",attendees:40,salesperson:"Arnab",reported:true,kols:["Dr. Vivek Agarwala"]},
{id:240,therapy:"Opthal",event:"Bayer I-Sight Meeting (8:30 pm) Hrishikesh",month:"May",date:"15-May-2026",type:"NSP",attendees:54,salesperson:"Hrishikesh",reported:true,kols:["Swakshyar Saumya Pal","Dr. Shuvenda Boral","Dr. Sudipta Das","Dr. Soumava Mandal"]},
{id:241,therapy:"Onco",event:"Prostate Cancer CME (7:00 pm) Vandna",month:"May",date:"15-May-2026",type:"NSP",attendees:76,salesperson:"Vandna",reported:true,kols:["Dr. Mintu Mathew Abraham","Dr. Mohammad Suhel","Dr. Nithin S.G"]},
{id:242,therapy:"Opthal",event:"Bayer I-Sight Meeting (8:30 pm) Sanjit",month:"May",date:"16-May-2026",type:"NSP",attendees:40,salesperson:"Sanjit",reported:true,kols:["Dr. Nabatika Mohanty","Dr. Gitumoni Sharma"]},
{id:243,therapy:"Opthal",event:"Bayer I-Sight Meeting (8:30 pm) Dhrubajit",month:"May",date:"18-May-2026",type:"NSP",attendees:39,salesperson:"Dhrubajit",reported:true,kols:["Dr. Suklengmung Buragohain","Dr. Deepak Agarwal"]},
{id:244,therapy:"Opthal",event:"Bayer I-Sight Meeting (8:00 pm) Srinivas",month:"May",date:"20-May-2026",type:"NSP",attendees:56,salesperson:"Srinivas",reported:true,kols:["Dr. T Krishna","Dr. S Srikanth","Dr. K Annaji Rao"]},
{id:245,therapy:"Opthal",event:"Bayer I-Sight Meeting (6:00 pm) Rajani (Only Link)",month:"May",date:"21-May-2026",type:"NSP",attendees:null,salesperson:"Rajani",reported:false,kols:["Dr. Tanvi Jain"]},
{id:246,therapy:"Opthal",event:"Bayer I-Sight Meeting (7:00 pm) Anil",month:"May",date:"22-May-2026",type:"NSP",attendees:22,salesperson:"Anil",reported:true,kols:["Dr. Navya Cherukuri"]},
{id:247,therapy:"Opthal",event:"Bayer I-Sight Meeting (8:30 pm) Abhishek",month:"May",date:"22-May-2026",type:"NSP",attendees:47,salesperson:"Abhishek",reported:true,kols:["Dr. Saptorshi Majumdar","Dr. Soumava Mandal","Dr. ManabJyoti Barman"]},
{id:248,therapy:"Opthal",event:"Bayer I-Sight Meeting (8:00 pm) Dinesh Mehta",month:"May",date:"23-May-2026",type:"NSP",attendees:44,salesperson:"Dinesh Mehta",reported:true,kols:["Dr. Tinku Bali","Dr. Basudha Jaiswal","Dr. Shivani"]},
{id:249,therapy:"Opthal",event:"Bayer I-Sight Meeting (8:45 pm) Abhishek",month:"May",date:"25-May-2026",type:"NSP",attendees:43,salesperson:"Abhishek",reported:true,kols:["Dr. Dinesh Rungta","Dr. Alok Agarwal"]},
{id:250,therapy:"Opthal",event:"Bayer I-Sight Meeting (8:00 pm) Srinivas",month:"May",date:"26-May-2026",type:"NSP",attendees:null,salesperson:"Srinivas",reported:false,kols:["Dr. Lohith Rambarki","Dr. N Praveen Kumar","Dr. Guru Sravan"]},
{id:251,therapy:"Opthal",event:"Bayer I-Sight Meeting (7:00 pm) Anil",month:"May",date:"27-May-2026",type:"NSP",attendees:null,salesperson:"Anil",reported:false,kols:["Dr. Sree Ram Charan"]},
{id:252,therapy:"Opthal",event:"Bayer I-Sight Meeting (8:00 pm) Yash",month:"May",date:"27-May-2026",type:"NSP",attendees:null,salesperson:"Yash",reported:false,kols:["Dr Prakhar Singhai","Dr Urmil Shah","Dr Harsha Jawarkar"]},
{id:253,therapy:"Opthal",event:"Bayer I-Sight Meeting (8:30 pm) Nitesh Kumar",month:"May",date:"28-May-2026",type:"NSP",attendees:null,salesperson:"Nitesh Kumar",reported:false,kols:["Dr. Debarati Dasgupta","Dr. Nishita Yadav"]},
{id:254,therapy:"Opthal",event:"Bayer I-Sight Meeting (8:00 pm) Srinivas",month:"June",date:"5-Jun-2026",type:"NSP",attendees:null,salesperson:"Srinivas",reported:false,kols:["Dr Lakshmi Prasanna S","Dr Sweta K","Dr Sai Divya N"]},
{id:255,therapy:"Opthal",event:"Bayer I-Sight Meeting (7:00 pm) Anil",month:"June",date:"28-Jun-2026",type:"NSP",attendees:null,salesperson:"Anil",reported:false,kols:["Dr. Vishal Raval"]}
];

// Dynamically built from data — auto-updates when sheet adds new months/years
let MONTH_ORDER = ['February','March','April','May','June','July','August','September','October','November','December','January'];

// ── SPEAKER GALLERY ────────────────────────────────
// Hardcoded Drive file IDs — no fetch needed, gallery loads instantly
const DRIVE_FILE_IDS = {
  'Dr Lakshmi Prasanna S': '1PPiqiidQiF298WL6iIWNMHW3qgkKDrJV',
  'Dr Rakesh Pinninti':    '1JkCVd0TpZ0J509hSeL_rIdCcoaYgyT5W',
  'Dr Ramesh Reddy':       '1cQDUbUinXM30Ze-eWOkukGHoAUovZA6e',
  'Dr Sai Divya N':        '1G24ct2Zz39FEdGBpPVrCl4wbrcCUsbfy',
  'Dr Sweta K':            '1fzwhSSwAlIRNhrNUfMqX8sbyByFudReK',
  'Dr Venugopal Arroju':   '1-5EW2PX7kjtoHTj_ua5R2P8y_397MBU0',
  'Dr. Debmalya Das':      '1OYgOoPn0_gLB8xTavhTCYUyKlzkZTkRD',
  'Dr. Kelvin Teo':        '1F2NhwGTX04pV4n3FBfaIBhEWFCZIcSPo',
  'Dr. Pranab Das':        '137RxIuYoy4p0Ee3Zug0mRq1M3M3uWr1y',
  'Dr. Shobhit Varma':     '1bxtxUHWvbUZ6O-LprQj_NZ3UtrzF4tJ7',
  'Dr. Subhadip Sarkar':   '1nUqQdYuEe7LBkrW0M04CJ8DCUdF8u-ge'
};

// Build drivePhotoMap at startup — no async fetch required
const drivePhotoMap = {};
Object.entries(DRIVE_FILE_IDS).forEach(([name, id]) => {
  drivePhotoMap[name.toLowerCase()] = {
    name,
    photoUrl: `https://drive.google.com/thumbnail?id=${id}&sz=w400-h400`
  };
});

// Credentials map and Sheet2 URL — must be declared before HARDCODED_CREDS
const credentialsMap = {};
const SHEET2_URL = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQYwkCYHxM0pGXyB6rh2-xiH_zpBkWrgx4s90SIs8yZpxvqvr-cYc_wP6omojYPKfgykiYNHOnwWrC1/pub?gid=967781355&single=true&output=csv';

// Hardcoded credentials — loaded instantly, no fetch needed
// fetchCredentials() below can add more from Sheet2 dynamically
const HARDCODED_CREDS = {
  'Dr Lakshmi Prasanna S': 'Consultant Vitreo Retinal Surgeon, Maxivision Eye Hospital, Visakhapatnam',
  'Dr Sweta K':            'Consultant Vitreo Retinal Surgeon, Vasan Eye Care, Vijayawada',
  'Dr Sai Divya N':        "Consultant Vitreo Retinal Surgeon, Dr Agarwal's Eye Hospital, Rajahmundry",
  'Dr. Pranab Das':        'Senior Vitreo Retina Surgeon, Center For Sight, Kolkata',
  'Dr. Debmalya Das':      'Senior Vitreo Retina Surgeon, Sankara Netralaya, New Town, Kolkata',
  'Dr. Subhadip Sarkar':   'Vitreo-Retinal & Phaco Consultant, Disha Eye Hospitals. MBBS – Nil Ratan Sircar Medical College, Kolkata. MS Ophthalmology – PMCH. SR (Vitreo-Retina) – RIO Kolkata. Asst. Professor – KPCMCH Kolkata',
  'Dr. Shobhit Varma':     'Vitreo-Retinal & Phaco Consultant, ASG Eye Hospitals. MBBS – Kasturba Medical College, Mangalore. DO – RIO RIMS Ranchi. DNB Ophthalmology – LVPEI Hyderabad. FVRS – SN Chennai. FICO (UK)',
  'Dr Ramesh Reddy':       'Consultant Medical Oncologist, Omega Hospitals, Tirupati',
  'Dr Rakesh Pinninti':    'Consultant Medical Oncologist, Basavatarakam Indo-American Cancer Hospital & Research Institute, Hyderabad',
  'Dr Venugopal Arroju':   'Consultant Medical Oncologist, Medicover Hospitals, Hyderabad',
  'Dr. Kelvin Teo':        'MBBS (London, UK), FAMS (Singapore), PhD (Sydney, Australia). Specialist Ophthalmologist, Senior Consultant, Advanced Adjunct Associate Professor, Duke NUS Eye ACP',
};
// Pre-populate credentialsMap so it's available before any fetch
Object.entries(HARDCODED_CREDS).forEach(([name, cred]) => {
  credentialsMap[name.toLowerCase()] = { credential: cred, hospital: '' };
});
